name: setup-node
description: "Setup Node.js and installing dependencies !!!"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Cache dependencies
      id: cache_dependencies
      uses: actions/cache@v4
      with:
        path: mk-test-daniel/node_modules
        key: node-modules-${{ hashFiles('mk-test-daniel/package-lock.json') }}

    - name: Install dependencies
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: mk-test-daniel 

